services:
  # --- O BANCO DE DADOS ---
  postgres:
    image: postgres:15
    container_name: renewable_energy_db
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_INITDB_ARGS=--encoding=UTF8 --locale=C
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - etl_network

  # --- ETL ---
  etl_app:
    build: .
    container_name: renewable_energy_etl
    depends_on:
      - postgres
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=${DATABASE_URL_DOCKER}
    networks:
      - etl_network

networks:
  etl_network:
    driver: bridge

volumes:
  postgres_data:
